version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CloudOfficeHours"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4arg7igkhapc"
s3_prefix = "CloudOfficeHours"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
